# Generated by Django 5.0.3 on 2024-04-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galleryimage_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technologies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
