# Generated by Django 5.0.6 on 2024-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_cartitem_cart_cart_items_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart', to='main.cartitem'),
        ),
    ]
