# Generated by Django 5.0.6 on 2024-06-16 17:51

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_cart_items_cart_user_cartitem_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=main.models.get_default_cart, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart'),
        ),
    ]
